### PR TITLE
Update templateDetails.xml

### PR DESCRIPTION
**Pull request by CSnipper**
1. Four new module positions
2. Google Web Fonts subsets
3. Logo types
4. Site slogan

### CODE REVIEW

**Comment by betweenbrain** [comment]
Hi CSnipper,

Thanks for taking the time and the effort that you put into creating a Pull Request! I really appreciate it and hope to see many more from Construct users . My apologies for the delay in responding, for some reason I wasn't receiving notifications from this repo.

If possible, I'd prefer to have these as separate PRs in case one item holds up the others up. But, we'll see if we can do it as one this time :-)
1. I don't see index.php having been modified. Do I understand correctly, for example in the case of `<div id="column-group-alpha" class="clearfix">`, that `top-left` would render first followed by `<div id="column-1" >` and `<div id="column-2"`? This is an interesting idea. While I have never needed such positions, others might. For the sake on consistency, I might call them something like `alpha-above`, `alpha-below`, `beta-above` or `beta-below`. Make sense?
2. I'm very happy to see the subsets issue being addressed, thanks! I assume that the idea behind this is to provide all possible options, while they might not exist for the font type? What happens if I choose a subset that doesn't exist for the font?
3. & 4. Look very interesting. I'm going to clone your fork and spend some time looking at it.

Thanks again, I'm excited to see more outside contributions!

**Comment by CSnipper** [comment]
Ups, I have forgotten about index.php ;) Just modified it, see my repo.

Subsets:

&subset=' . $googleWebFontSubset . '

change to:

&subset=latin,' . $googleWebFontSubset . '

and now latin is always loaded, and your chosen subset is loaded as second option. 

I'm not a programmer, but it could be possible to load from json only subsets avaliable with chosen font but it can be done in javascript not in php I guess.

**Comment by betweenbrain** [comment]
I like that approach. I think I'd take it one step further, which I can do on my end, and default to Latin if no subset is decalared, just in case someone doesn't want to use Latin (i.e. `<link href='http://fonts.googleapis.com/css?family=Marcellus+SC&subset=latin-ext' rel='stylesheet' type='text/css'>`)

**Comment by betweenbrain** [comment]
Hi CSnipper,

FYI, I have cherry picked the Google Web Font subset contribution to the 3-0 branch and will back-port it to the others. I added a default option of `Default`, with no value, to accommodate situations where we don't need subset defined.

I'm going to work on pulling in the module positions next.

Thanks again!

**Comment by CSnipper** [comment]
Great!

2012/11/7 Matt Thomas notifications@github.com

**Comment by betweenbrain** [comment]
Closing this as it can'r be merged automatically, but will take under consideration for future releases.

**Pull request closed without merging**
